version: "3.9"

services:
  app:
    container_name: app
    build:
      context: ../app
      dockerfile: ../docker/dockerfiles/app
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app:delegated
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}

      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=5432
      - DB_TEST=my_tdd_test
    tty: true
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgres:11.12-alpine"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data/:delegated
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbdata:
